spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Seoul&?useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      connection-timeout: 5000
      auto-commit: false
      # reference: https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

app:
  auth:
    access-token:
      secret: some-secret-value
